# SI 330: Homework 6: Numpy arrays and vectorization


## Due: Friday, October 26, 2018,  11:59:00pm

### Submission instructions
After completing this homework, you will turn in two files via Canvas ->  Assignments -> HW 6:
- Your Notebook, named si330-hw6-YOUR_UNIQUE_NAME.ipynb and
- the HTML file, named si330-hw6-YOUR_UNIQUE_NAME.html.

### Name:  Samantha Cohen
### Uniqname: samcoh
### People you worked with: Rhea and Emil

## Top-Level Goal
To practice using numpy arrays and vectorizations



## Learning Objectives
After completing this Lab, you should know how to:
* perform basic vectorized math with numpy arrays
* filter numpy arrays



## Part 0: Setup

In [2]:
import numpy as np
import pandas as pd
from collections import defaultdict

In this assignment, we will load in some data from the following data frame, which contains the properties of several different car models, such as their number of cylinders, their miles per gallon, etc.

In [3]:
cars = pd.read_csv("mtcars.csv")
cars

car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

**IMPORTANT**: Even though we are loading the data into a data frame initially, we are going to pull out a couple of columns as numpy arrays.

**You will write all of your answers using those arrays, not the data frame.** The purpose of this assignment is to practice using arrays, so **DO NOT** use the above data frame to answer any of the questions below. Only use the following vectors that we will create from the data frame:

In [4]:
car = cars["car"].values
mpg = cars["mpg"].values
cyl = cars["cyl"].values
hp = cars["hp"].values
gear = cars["gear"].values
cars = None     # just to make sure you don't accidentally use the data frame :) 

The variables we are going to use are...

The number of cylinders in each car, `cyl`:

In [5]:
cyl

array([6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,
       8, 8, 8, 4, 4, 4, 8, 6, 8, 4])

The miles per gallon of each car, `mpg`:

In [6]:
mpg

array([21. , 21. , 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8,
       16.4, 17.3, 15.2, 10.4, 10.4, 14.7, 32.4, 30.4, 33.9, 21.5, 15.5,
       15.2, 13.3, 19.2, 27.3, 26. , 30.4, 15.8, 19.7, 15. , 21.4])

The horsepower of each car, `hp`:

In [7]:
hp

array([110, 110,  93, 110, 175, 105, 245,  62,  95, 123, 123, 180, 180,
       180, 205, 215, 230,  66,  52,  65,  97, 150, 150, 245, 175,  66,
        91, 113, 264, 175, 335, 109])

The number of gears in each car, `gear`:

In [8]:
gear

array([4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3,
       3, 3, 3, 4, 5, 5, 5, 5, 5, 4])

The name of each car, `car`:

In [9]:
car

array(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D',
       'Merc 230', 'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL',
       'Merc 450SLC', 'Cadillac Fleetwood', 'Lincoln Continental',
       'Chrysler Imperial', 'Fiat 128', 'Honda Civic', 'Toyota Corolla',
       'Toyota Corona', 'Dodge Challenger', 'AMC Javelin', 'Camaro Z28',
       'Pontiac Firebird', 'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa',
       'Ford Pantera L', 'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype=object)

Note that these variables have *parallel indices*; that is, if `car[3]` is the name of the 4th car, `mpg[3]` is the number of miles per gallon of that car, and `cyl[3]` is the number of cylinders in that car.

### Part 1: Questions

**Q1.** Write a single expression that returns a numpy array containing the unique values of `cyl`. 

*Hint:* look up the `numpy.unique` function.

In [11]:
np.unique(cyl)
#cyl

array([4, 6, 8])

**Q2.** Write a single expression that returns a numpy array of all values of `mpg` where the number of cylinders in the car is 4.

In [19]:
mpg[cyl==4]



array([22.8, 24.4, 22.8, 32.4, 30.4, 33.9, 21.5, 27.3, 26. , 30.4, 21.4])

**Q3.** Write a single expression that returns a python list of numpy arrays, where there is one entry in the list for each unique value of `cyl`. Each list entry should be a numpy array containing all of the values of `mpg` for some unique value of `cyl`. 

*Hint 1:* You should end up with a list the contains three elements, each of which is a numpy array of `mpg` values.

*Hint 2:* Your answers to the previous two questions should help you here.

*Hint 3:* You can iterate over the values in a numpy array using a list comprehension.

In [11]:
[mpg[cyl==unique] for unique in np.unique(cyl)]  


[array([22.8, 24.4, 22.8, 32.4, 30.4, 33.9, 21.5, 27.3, 26. , 30.4, 21.4]),
 array([21. , 21. , 21.4, 18.1, 19.2, 17.8, 19.7]),
 array([18.7, 14.3, 16.4, 17.3, 15.2, 10.4, 10.4, 14.7, 15.5, 15.2, 13.3,
        19.2, 15.8, 15. ])]

**Q4.** Complete this sentence describing what the following code does. It should be *one* sentence.

> It creates a dictionary where the keys are cylinders and the values are a list of mpgs that correspond to the cars with that number of cyclinders. 

In [12]:
d = defaultdict(list)
for i in range(len(cyl)):
    d[cyl[i]].append(mpg[i])
print(d)

defaultdict(<class 'list'>, {6: [21.0, 21.0, 21.4, 18.1, 19.2, 17.8, 19.7], 4: [22.8, 24.4, 22.8, 32.4, 30.4, 33.9, 21.5, 27.3, 26.0, 30.4, 21.4], 8: [18.7, 14.3, 16.4, 17.3, 15.2, 10.4, 10.4, 14.7, 15.5, 15.2, 13.3, 19.2, 15.8, 15.0]})


**Q5.** What would a better name for the variable `d` be? Make it descriptive but succinct. Think about what its keys and values are...

> A better name for `d` is ... Dict_Maps_Cylinders_to_ListofMPGs

**Q6.** Write a single expression that creates essentially the same data structure as the code in **Q4**, but does so in a single line. *There should be one difference in your output:* the values containg in the dictionary should be numpy arrays instead of lists.

*Hint 1:* Your answers to questions 1, 2, and 3 should help you here.

In [13]:
{x: [mpg[cyl==x]] for x in cyl} 



{6: [array([21. , 21. , 21.4, 18.1, 19.2, 17.8, 19.7])],
 4: [array([22.8, 24.4, 22.8, 32.4, 30.4, 33.9, 21.5, 27.3, 26. , 30.4, 21.4])],
 8: [array([18.7, 14.3, 16.4, 17.3, 15.2, 10.4, 10.4, 14.7, 15.5, 15.2, 13.3,
         19.2, 15.8, 15. ])]}

**Q7.** Write a single expression that creates a dictionary where the keys are unique values of `cyl` and the values are the mean miles per gallon for cars with that number of cylinders.

*Hint 1:* Read up on `numpy.mean()`

In [14]:
{x: np.mean(mpg[cyl==x]) for x in cyl}


{6: 19.74285714285714, 4: 26.66363636363636, 8: 15.1}

**Q8.** Write a single expression that creates a dictionary where the keys are unique values of `cyl` and the values are the mean horsepower (`hp`) of cars with that number of cylinders.

In [15]:
{x: np.mean(hp[cyl == x]) for x in cyl}


{6: 122.28571428571429, 4: 82.63636363636364, 8: 209.21428571428572}

**Q9.** Write a single expression that creates a dictionary where the keys are unique values of `gear` and the values are the **MAXIMUM** miles per gallon of any car with that number of gears.

In [16]:
{x: np.max(mpg[gear == x]) for x in gear}

{4: 33.9, 3: 21.5, 5: 30.4}

**Q10.** What is the name of the car with the highest number of miles per gallon? Write a single expression to output the name.

*Hint:* Look up the `numpy.argmax()` method.

In [17]:
car[np.argmax(mpg)]

'Toyota Corolla'

## Bonus

**Q11**. Cars with how many cylinders tend to have the highest miles per gallon, on average? Write a single expression to output the miles per gallon and number of cylinders.

In [18]:
[(np.max([np.mean(mpg[cyl==x]) for x in cyl]),x) for x in np.unique(cyl) if np.mean(mpg[cyl==x]) == np.max([np.mean(mpg[cyl==x]) for x in cyl])]

[(26.66363636363636, 4)]