# Lab 6 - Vectorization


## Due: Thursday, Oct 18, 2018, 11:59:00pm

### Submission instructions
After completing this homework, you will turn in two files via Canvas ->  Assignments -> Lab 6:
Your Notebook, named si330-lab6-YOUR_UNIQUE_NAME.ipynb and
the HTML file, named si330-lab6-YOUR_UNIQUE_NAME.html

### Name:  Samantha Cohen 
### Uniqname: samcoh
### People you worked with: I worked by myself


## Objectives
After completing this Lab, you should know how to use numpy arrays to:
* Perform basic vectiorized arithmetic and boolean operations on an array
* Filter arrays using vectorized operations

## Part 0: Setup

In [1]:
import numpy as np

## Part 1

### Q1.1 - add 3 to every element of list `start_list1` (comprehension)

Convert the code below to use a **comprehension** instead of a for loop.
The result should be a python list.

In [2]:
start_list1 = [5, 2, 1, 8, 4, 6]

#result = []
#for element in start_list1:
    #result.append(element + 3)
#print(result)
result = [element + 3 for element in start_list1]
result

[8, 5, 4, 11, 7, 9]

### Q1.2 - add 3 to every element of list `start_list1` (vectorization)

Convert the code below to use **vectorization** instead of a for loop.
The result should be a numpy array.

In [3]:
start_list1 = [5, 2, 1, 8, 4, 6]

# result = []
# for element in start_list1:
#     result.append(element + 3)
# print(result)
result = np.array(start_list1)
result2=result + 3 
result2


array([ 8,  5,  4, 11,  7,  9])

### Q2.1 - multiply every element of list `start_List2` by 2 (for loop)

Convert the code below to use **a for loop** instead of a comprehension.
The result should be a python list.

In [4]:
start_list2 = [2, 4, 7, 2, 6, 1]

#print([element * 2 for element in start_list2])
result = [] 
for element in start_list2: 
    result.append(element * 2)
result
    

[4, 8, 14, 4, 12, 2]

### Q2.2 - multiply every element of list `start_List2` by 2 (vectorization)

Convert the code below to use **vectorization** instead of a comprehension.
The result should be a numpy array.

In [5]:
start_list2 = [2, 4, 7, 2, 6, 1]

#print([element * 2 for element in start_list2])
result = np.array(start_list2) 
result2 =result * 2 
result2

array([ 4,  8, 14,  4, 12,  2])

### Q3.1 - raise every element of list `start_list3` to the power of 2 (for loop)

Convert the code below to use **a for loop** instead of a comprehension.
The result should be a python list.

In [6]:
start_list3 = [1, 2, 3, 4]

#print([element * element for element in start_list3])
result =[] 
for element in start_list3: 
    result.append(element *element)
result
    

[1, 4, 9, 16]

### Q3.2 - raise every element of list `start_list3` to the power of 2 (vectorization)

Convert the code below to use **vectorization** instead of a comprehension.
The result should be a numpy array.

In [7]:
start_list3 = [1, 2, 3, 4]

#print([element * element for element in start_list3])
result = np.array(start_list3)
result2 = result * result
result2

array([ 1,  4,  9, 16])

### Q4.1 - filter the list `start_list4` so that every element is > 5 (comprehension)

Convert the code below to use **a comprehension** instead of a for loop.
The result should be a python list.

In [8]:
start_list4 = [1, 25, 7, 13, 4]

# result = []
# for element in start_list4:
#     if element > 5:
#         result.append(element)
# print(result)
result = [element for element in start_list4 if element > 5]
print(result)

[25, 7, 13]


### Q4.2 - filter the list `start_list4` so that every element is > 5 (vectorization)

Convert the code below to use **vectorization** instead of a for loop.
The result should be a numpy array.

In [9]:
start_list4 = [1, 25, 7, 13, 4]

# result = []
# for element in start_list4:
#     if element > 5:
#         result.append(element)
# print(result)
result = np.array(start_list4)
result2=result[result > 5]
result2

array([25,  7, 13])

### Q5 - filter the list `start_list5` so that every element is > 2 and < 7 (vectorization)

Convert the code below to use **vectorization** instead of a comprehension.
The result should be a numpy array.

In [10]:
start_list5 = [5, 2, 1, 8, 4, 6]

#print([element for element in start_list5 if 2 < element < 7])
result = np.array(start_list5)
result2=result[(2<result)&(result < 7)]

result2

array([5, 4, 6])

### Q6.1 - add the corresponding elements of two lists, `start_list6a` and `start_list6b` (vectorization)

Convert the code below to use **vectorization** instead of a for loop.
The result should be a numpy array.

In [11]:
start_list6a = [5, 2, 1, 8, 4]
start_list6b = [1, 2, 3, 4, 5]

# result = []
# for i in range(len(start_list6a)):
#     result.append(start_list6a[i] + start_list6b[i])
# print(result)

result1 = np.array(start_list6a)
result2= np.array(start_list6b)
result3 =result1+result2
result3

array([ 6,  4,  4, 12,  9])

## Part 2: BONUS

### Q6.2 (Bonus) - add the corresponding elements of two lists, `start_list6a` and `start_list6b` (comprehension)

Convert the code below to use **a single comprehension** instead of a for loop.
The result should be a python list.

In [12]:
start_list6a = [5, 2, 1, 8, 4]
start_list6b = [1, 2, 3, 4, 5]

# result = []
# for i in range(len(start_list6a)):
#     result.append(start_list6a[i] + start_list6b[i])
# print(result)

result = [start_list6a[i] + start_list6b[i] for i in range(len(start_list6a))]
print(result)

[6, 4, 4, 12, 9]


### Q7 (Bonus) - filter the list `start_list7` so that every element is divisible by 2

Write the code below using **vectorization**. The result should be a numpy array.

In [13]:
start_list7 = np.array([5, 2, 1, 8, 4])

# INSERT CODE HERE...
result = start_list7[start_list7%2 ==0]
result

array([2, 8, 4])

### Q8 (Bonus 2) - filter the list `start_list8` to contain only elements that are greater than or equal to their corresponding element (same index) in list `minimum` AND less than or equal to their corresponding element in list `maximum`.

Write the code below using **vectorization**. The result should be a numpy array.

In [14]:
start_list8 = np.array([3, 6, 6, 2, 3, 5])
minimum = np.array([0, 7, 2, 5, 3, 4])
maximum = np.array([4, 9, 6, 10, 7, 6])

# INSERT CODE HERE...
result =start_list8[(start_list8 >= minimum )& (start_list8 <= maximum)]
result

array([3, 6, 3, 5])